Fix footer
WildCodeSchool/202302-orleans-php-project2-ahls pull request #11
Opened 2023-04-21 14:34 UTC by bugBuster42

2023-04-21 15:16 UTC, JorisPineau approved these changes

2023-04-26 07:11 UTC, jaalazard approved these changes
ok

2023-04-26 14:47 UTC, sblondeau requested changes
problème dans le nom de la branche ? j'ai fix_footer alors qu'au final j'ai une US sur les membres ?

2023-04-26 14:47 UTC, sblondeau commented on public/assets/css/association.css
> +    /*display: flex;
code commenté, à retirer

2023-04-26 14:47 UTC, sblondeau commented on public/assets/images/boardMember_placeholder.jpg
trop gros cette image

2023-04-26 14:47 UTC, sblondeau commented on src/View/Association/index.html.twig
> +						<img src="{{ boardMember.image ?? 'assets/images/vector.png'}}" alt="">
tu affiches 2 fois le bordMember.image

2023-04-26 16:49 UTC, sblondeau approved these changes

2023-04-27 12:48 UTC, merged