magazine section for homepage
WildCodeSchool/202302-orleans-php-project2-ahls pull request #17
Opened 2023-04-26 12:59 UTC by ElBarto444

2023-04-26 13:09 UTC, JorisPineau submitted a review, later dismissed

2023-04-27 12:07 UTC, jaalazard approved these changes

2023-04-27 12:23 UTC, bugBuster42 approved these changes

2023-05-02 08:26 UTC, Zakari-B commented
ON NE FAIT PAS DE RESOLUTION DE CONFLIT SANS NOTRE ACCORD.

2023-05-02 08:37 UTC, Zakari-B requested changes

2023-05-02 08:37 UTC, Zakari-B commented on .gitignore
> +$myConnection.session.sql
lignes dupliquées

2023-05-02 08:37 UTC, Zakari-B commented on public/assets/css/magazine.css
> +
Pas de lignes vides en début de fichier.

2023-05-02 08:37 UTC, Zakari-B commented on public/assets/css/magazine.css
> +    /*gap: calc(var(--spacing) * 1);*/
Pas de code commenté.

2023-05-02 08:37 UTC, Zakari-B commented on public/assets/css/style.css
> +
Pas de lignes vides en début de fichier.

2023-05-02 08:37 UTC, Zakari-B commented on src/View/Home/index.html.twig
>  	<link rel="stylesheet" href="/assets/css/home/header.css">
Pas besoin de parent() dans vos stylesheets ? Vous avez le css de navbar et footer dans le layout.

2023-05-03 07:13 UTC, bugBuster42 submitted a review, later dismissed

2023-05-03 07:14 UTC, bugBuster42 approved these changes

2023-05-03 12:53 UTC, jaalazard approved these changes

2023-05-03 12:54 UTC, JorisPineau approved these changes

2023-05-03 13:41 UTC, Zakari-B requested changes

2023-05-03 13:41 UTC, Zakari-B commented on $myConnection.session.sql
C'est quoi ce fichier vide ? A retirer.

2023-05-03 13:41 UTC, Zakari-B commented on src/View/Home/index.html.twig
>  	<link rel="stylesheet" href="/assets/css/home/header.css">
Les modifications ne sont pas du tout ce que j'attendais... Il ne faut pas remettre navbar et footer ici, ils sont déjà dans le layout. Par contre, dans le layout ils devraient être DANS le bloc stylesheet, et vous l'appelez ici avec parent() pour reprendre le css présent dans le layout et y ajouter les feuilles de style supplémentaires nécessaires à cette page.

2023-05-03 13:41 UTC, Zakari-B commented on src/View/layout.html.twig
> +		<link rel="stylesheet" href="/assets/css/navbar.css">
Dans le bloc de style.

2023-05-04 10:17 UTC, JorisPineau approved these changes

2023-05-04 10:17 UTC, jaalazard submitted a review, later dismissed

2023-05-04 18:36 UTC, sblondeau commented on src/View/Home/index.html.twig
> +						<img src="https://nzentrepreneur.co.nz/wp-content/uploads/2022/08/Partner-Logo-placeholder-300x157.png" alt="{{ partner.name }}">
tu ne dois pas aller chercher l'image du placeholder en ligne, mais la télécharger dans assets/images. Car si le site que tu cibles enlève l'image, ça ne fonctionne plus chez toi

2023-05-09 07:20 UTC, bugBuster42 approved these changes

2023-05-09 08:11 UTC, jaalazard approved these changes

2023-05-09 08:20 UTC, sblondeau requested changes

2023-05-09 08:20 UTC, sblondeau commented on public/assets/css/style.css
>      --primary-color: rgb(171, 150, 97);
tjs le pb de quotes

2023-05-10 08:13 UTC, closed without merging