ajouter un partenaire
WildCodeSchool/202302-orleans-php-project2-ahls pull request #23
Opened 2023-04-28 09:04 UTC by jaalazard

2023-04-28 09:07 UTC, jaalazard reviewed
Bon travail

2023-04-28 09:31 UTC, bugBuster42 approved these changes

2023-04-28 14:04 UTC, sblondeau requested changes

2023-04-28 14:04 UTC, sblondeau commented on src/Controller/AdminPartnerController.php
> +                $errors[] = "Votre fichier doit faire moins de 2M !";
moins de ' . $maxFileSize/1000000

2023-04-28 14:04 UTC, sblondeau commented on src/View/Home/Item/add.html.twig
> +{% extends 'layout.html.twig' %}
tu as du déplacer encore par erreur le dossier template des Items View/Items dans le dossier View/Home

2023-04-28 14:23 UTC, ElBarto444 approved these changes
Génial !!

2023-04-28 14:56 UTC, ElBarto444 submitted a review, later dismissed
C'est beaucoup mieux comme ça, merci mille fois

2023-04-28 15:03 UTC, JorisPineau submitted a review, later dismissed

2023-05-02 07:39 UTC, Zakari-B requested changes

2023-05-02 07:39 UTC, Zakari-B commented on src/Controller/AdminPartnerController.php
> +            // TODO validations (length, format...)
Les validations sont faites, ce commentaire n'a plus lieu d'être.

2023-05-02 07:39 UTC, Zakari-B commented on src/View/Admin/Partner/_form.html.twig
> +    </div>
Petit souci d'indentation sur cette div.

2023-05-02 07:39 UTC, Zakari-B commented on src/View/Admin/Partner/_form.html.twig
> +	<form method="post" action="" enctype="multipart/form-data" novalidate>
On ne laisse pas le novalidate !!!!!!
Problème d'indentation sur le form et pourquoi cette div.formulaire ?

2023-05-03 07:12 UTC, bugBuster42 submitted a review, later dismissed

2023-05-03 10:16 UTC, Zakari-B requested changes

2023-05-03 10:16 UTC, Zakari-B commented on src/View/Admin/Partner/_form.html.twig
> +	<form method="post" action="" enctype="multipart/form-data">
Problème d'indentation sur le form.

2023-05-03 10:36 UTC, sblondeau submitted a review, later dismissed

2023-05-03 13:58 UTC, merged