footer
WildCodeSchool/202302-orleans-php-project2-ahls pull request #3
Opened 2023-04-14 08:13 UTC by bugBuster42

2023-04-14 08:19 UTC, jaalazard approved these changes
ok

2023-04-14 08:20 UTC, ElBarto444 approved these changes
ok

2023-04-14 08:22 UTC, JorisPineau approved these changes

2023-04-14 08:37 UTC, Zakari-B requested changes

2023-04-14 08:37 UTC, Zakari-B commented on public/assets/css/footer.css
> +    font-size: 3rem;
Variable pour la taille de police

2023-04-14 08:37 UTC, Zakari-B commented on public/assets/css/footer.css
> +    font-size: 1.5rem;
Variable pour la taille de police

2023-04-14 08:37 UTC, Zakari-B commented on public/assets/css/footer.css
> +    gap: 2rem;
Utilisez la variable spacing ici.

2023-04-14 08:37 UTC, Zakari-B commented on public/assets/css/footer.css
> +    min-width: 35px;
Testez en mettant la taille sur l'img directement.

2023-04-14 09:01 UTC, jaalazard submitted a review, later dismissed
ok

2023-04-14 09:07 UTC, ElBarto444 submitted a review, later dismissed
ok

2023-04-14 09:37 UTC, Zakari-B requested changes

2023-04-14 09:37 UTC, Zakari-B commented on public/assets/css/style.css
> +    --third-color: #ab9661;
Par  cohérence, rgb comme les autres, pas héxa.

2023-04-19 09:59 UTC, bugBuster42 commented on public/assets/css/footer.css
> +    min-width: 35px;
Pas réussi à garder le responsive des logos en ciblant directement l'image...

2023-04-19 10:11 UTC, ElBarto444 submitted a review, later dismissed
ok.

2023-04-19 10:11 UTC, JorisPineau approved these changes

2023-04-19 10:45 UTC, sblondeau requested changes

2023-04-19 10:45 UTC, sblondeau commented on src/View/components/_footer.html.twig
> +	</li>
li en trop ?

2023-04-19 10:45 UTC, sblondeau commented on src/View/layout.html.twig
> +			{% block footer %}
tu mets ton footer avant ton content là ! c'est après plutot

2023-04-19 12:54 UTC, jaalazard commented
ok

2023-04-19 12:55 UTC, jaalazard approved these changes
ok

2023-04-20 13:39 UTC, ElBarto444 approved these changes
ok.

2023-04-20 13:39 UTC, jaalazard approved these changes
ok

2023-04-20 14:02 UTC, sblondeau approved these changes

2023-04-20 14:02 UTC, merged