admin list journaux
WildCodeSchool/202302-orleans-php-project2-ahls pull request #31
Opened 2023-05-02 08:53 UTC by JorisPineau

2023-05-02 10:14 UTC, Zakari-B requested changes

2023-05-02 10:14 UTC, Zakari-B commented on src/View/adminLayout.html.twig
A supprimer, n'apporte strictement rien de plus par rapport au layout.

2023-05-02 10:14 UTC, Zakari-B commented on src/View/base.html.twig
A supprimer et repasser sur le layout standard.

2023-05-02 10:14 UTC, Zakari-B commented on src/View/layout.html.twig
A restaurer.

2023-05-02 10:14 UTC, Zakari-B commented on src/View/Admin/Newspaper/index.html.twig
> +{% extends 'adminLayout.html.twig' %}
layout.

2023-05-03 10:20 UTC, jaalazard approved these changes

2023-05-03 10:20 UTC, ElBarto444 approved these changes

2023-05-03 10:47 UTC, sblondeau requested changes

2023-05-03 10:47 UTC, sblondeau commented on src/Model/NewspaperManager.php
> +    public function selectAll(string $orderBy = 'number ', string $direction = 'DESC'): array
non tu reprends exactement le selecAll de l'AbstractManager en changeant juste la valeur par défaut des paramètres... ça ne sert à rien, il faut que tu l'enlève et utilise correctement le selectAll fourni en faisant
$newspaperManager->selectAll('number', 'DESC');

2023-05-03 12:49 UTC, bugBuster42 approved these changes

2023-05-03 12:52 UTC, jaalazard approved these changes

2023-05-03 13:35 UTC, jaalazard approved these changes

2023-05-03 13:58 UTC, merged