Ajouter des journaux
WildCodeSchool/202302-orleans-php-project2-ahls pull request #35
Opened 2023-05-03 15:02 UTC by JorisPineau

2023-05-03 15:03 UTC, jaalazard submitted a review, later dismissed

2023-05-03 15:04 UTC, bugBuster42 submitted a review, later dismissed

2023-05-03 20:29 UTC, sblondeau requested changes

2023-05-03 20:29 UTC, sblondeau commented on src/View/Admin/Newspaper/_form.html.twig
> +    <input type="text" id="link" name="link" value="{{ newspaper.link }}" required>
type="url"

2023-05-03 20:29 UTC, sblondeau commented on src/View/Admin/Newspaper/_form.html.twig
> +    <input type="text" id="date" name="date" value="{{ newspaper.date }}" required>
type="date"

2023-05-04 07:55 UTC, ElBarto444 submitted a review, later dismissed

2023-05-04 07:55 UTC, jaalazard approved these changes

2023-05-04 08:36 UTC, sblondeau requested changes

2023-05-04 08:36 UTC, sblondeau commented on src/View/Admin/Newspaper/_form.html.twig
> +    <input type="text" id="date" name="date" value="{{ newspaper.date }}" required>
pas fait!

2023-05-04 10:17 UTC, jaalazard submitted a review, later dismissed

2023-05-04 10:17 UTC, ElBarto444 approved these changes

2023-05-04 10:23 UTC, sblondeau requested changes

2023-05-04 10:23 UTC, sblondeau commented on src/View/Admin/Newspaper/index.html.twig
> +{% set month_translantion = {
a enlever du coup ?

2023-05-04 10:23 UTC, sblondeau commented on src/View/Admin/Newspaper/_form.html.twig
> +    <input type="date" id="date" name="date" value="{{ newspaper.date }}" required>
manque le format de date ?

2023-05-04 10:30 UTC, jaalazard approved these changes

2023-05-04 18:38 UTC, sblondeau approved these changes

2023-05-04 18:39 UTC, merged