S04US37 add finish
WildCodeSchool/202302-orleans-php-project2-ahls pull request #36
Opened 2023-05-03 15:26 UTC by bugBuster42

2023-05-03 15:27 UTC, JorisPineau approved these changes

2023-05-03 15:27 UTC, ElBarto444 approved these changes

2023-05-03 20:31 UTC, sblondeau requested changes

2023-05-03 20:31 UTC, sblondeau commented on src/Controller/AdminAssociationController.php
> +            if (empty($boardMember['lastname'])) {
manque la validation des longueur de chaines de caractères, en fonction du varchar que tu as mis en database

2023-05-03 20:31 UTC, sblondeau commented on src/Controller/AdminAssociationController.php
> +            if (empty($boardMember['lastname'])) {
à faire pour les 3 champs

2023-05-03 20:31 UTC, sblondeau commented on src/Controller/AdminAssociationController.php
> +            'errors' => $errors,
tu n'envoies pas boardMember à ta vue donc tu ne peux rien afficher dans les value des champs de form si erreur

2023-05-04 07:56 UTC, jaalazard approved these changes

2023-05-04 08:30 UTC, ElBarto444 approved these changes

2023-05-04 08:31 UTC, JorisPineau approved these changes

2023-05-04 08:31 UTC, jaalazard approved these changes

2023-05-04 08:37 UTC, sblondeau approved these changes

2023-05-04 08:37 UTC, merged