Ajout de la navbar et du responsive
WildCodeSchool/202302-orleans-php-project2-ahls pull request #4
Opened 2023-04-14 09:16 UTC by JorisPineau

2023-04-14 09:17 UTC, jaalazard approved these changes
Nice

2023-04-14 09:39 UTC, Zakari-B requested changes

2023-04-14 09:39 UTC, Zakari-B commented on public/assets/css/navbar.css
> +    font-size: 2rem;
font-size en variable

2023-04-14 12:57 UTC, ElBarto444 submitted a review, later dismissed

2023-04-14 13:08 UTC, bugBuster42 approved these changes

2023-04-19 12:11 UTC, sblondeau requested changes

2023-04-20 13:36 UTC, jaalazard submitted a review, later dismissed
ok

2023-04-20 14:03 UTC, sblondeau requested changes
modifs demandées non prises en compte

2023-04-20 21:04 UTC, sblondeau submitted a review, later dismissed

2023-04-21 08:22 UTC, jaalazard approved these changes
ok

2023-04-21 08:25 UTC, merged