legal_notice html css finish
WildCodeSchool/202302-orleans-php-project2-ahls pull request #42
Opened 2023-05-06 12:48 UTC by bugBuster42

2023-05-06 16:04 UTC, jaalazard approved these changes

2023-05-06 16:44 UTC, JorisPineau approved these changes

2023-05-07 18:48 UTC, sblondeau requested changes

2023-05-07 18:48 UTC, sblondeau commented on public/assets/css/legalNotice.css
> +.presentation {
code commenté à enlever !

2023-05-07 18:48 UTC, sblondeau commented on src/View/components/_footer.html.twig
> +			<a href="http://localhost:8000/mention">Mentions légales</a>
pas de localhost:8000 ! juste /mention. Sinon une fois le site en ligne, l'adresse étant www.ahls.fr ça marcherait plus

2023-05-09 07:14 UTC, ElBarto444 approved these changes

2023-05-09 07:14 UTC, JorisPineau approved these changes

2023-05-09 07:20 UTC, sblondeau approved these changes

2023-05-09 07:20 UTC, merged