S05 u25 create actuality
WildCodeSchool/202302-orleans-php-project2-ahls pull request #45
Opened 2023-05-07 11:53 UTC by ElBarto444

2023-05-07 11:58 UTC, jaalazard approved these changes

2023-05-07 16:14 UTC, JorisPineau approved these changes

2023-05-08 12:32 UTC, sblondeau requested changes

2023-05-08 12:32 UTC, sblondeau commented on public/assets/css/style.css
> +[data-theme=“light”],
attention c'est pas le bon type de quote, ils sont "penchés" là, idem la ligne au dessous

2023-05-08 12:32 UTC, sblondeau commented on src/Controller/AdminActualityController.php
> +        if (empty($article['date'])) {
tu ne verifie pas que la date a un format de date valide (par ex si on met le 30 février ça devrait planter)
pour ça une solution est de passer par un objet Datetime
$date = new Datetime($article['date']);
puis tu as une méthode getLastErrors() qui est empty si pas d'erreur, sinon contient les infos sur le pb de date éventuel.
Donc tu enchaine avec qq chose comme if(!empty($date->getLastErrors()) { alors $errors[] = 'Mauvais format de date';)
je te laisse rechercher dans la doc et adapter

2023-05-09 07:28 UTC, ElBarto444 commented on src/Controller/AdminActualityController.php
> +        if (empty($article['date'])) {
Je viens de tester avec le formulaire par défaut de pico et il y a déjà une sécurité pour éviter les saisies incorrectes sur les dates, je fais quand même les modifs ou je peux laisser tel quel ?

2023-05-09 07:30 UTC, jaalazard approved these changes

2023-05-09 08:05 UTC, JorisPineau approved these changes

2023-05-09 08:06 UTC, bugBuster42 submitted a review, later dismissed

2023-05-09 08:08 UTC, sblondeau approved these changes

2023-05-09 08:09 UTC, sblondeau commented
je te le passe parce que c'est la fin, mais beaucoup trop de fichiers modifiés dans cette PR, tu le vois au nombre de conflits que ça te génère... en faire trop d'un coup ne te fait pas gagner du temps ;-)

2023-05-09 08:54 UTC, merged