news feed block for homepage
WildCodeSchool/202302-orleans-php-project2-ahls pull request #5
Opened 2023-04-20 09:18 UTC by ElBarto444

2023-04-20 13:35 UTC, jaalazard submitted a review, later dismissed
ok

2023-04-20 13:39 UTC, bugBuster42 approved these changes

2023-04-20 14:11 UTC, sblondeau requested changes

2023-04-20 14:11 UTC, sblondeau commented on $myConnection.session.sql
c'est quoi ce fichier

2023-04-20 14:11 UTC, sblondeau commented on .tours/simple-mvc.tour
ce fichier devrait pas etre modifié et donc pas se retrouvé sur cette PR

2023-04-20 14:11 UTC, sblondeau commented on ahls.db
??

2023-04-20 14:11 UTC, sblondeau commented on public/assets/css/actuality.css
> +    background-color: #FFFEF5;
couleur en variable css stp

2023-04-20 14:11 UTC, sblondeau commented on public/assets/css/actuality.css
> +    font-size: clamp(2.1736rem, 1.5765rem + 1.9109vw, 3.0096rem);
j'aurais mis entre 2.1735 et 3.2356 perso...
pourquoi tu me fais ça ? :'(

2023-04-20 14:11 UTC, sblondeau commented on public/assets/css/actuality.css
> +    font-size: clamp(1.1rem, 0.8rem + 1.3333vw, 1.8rem);
idem, pas de .333333 au moins arrondi à 1.3vw

2023-04-20 14:11 UTC, sblondeau commented on public/assets/css/actuality.css
> +    font-size: clamp(1.1rem, 0.8rem + 1.3333vw, 1.8rem);
ou 4vw / 3

2023-04-20 14:11 UTC, sblondeau commented on public/assets/css/actuality.css
> +    color: #AB9661;
en variable

2023-04-20 14:11 UTC, sblondeau commented on public/assets/css/actuality.css
> +    background-color: #f1f1f1;
en variable

2023-04-20 14:11 UTC, sblondeau commented on public/assets/images/l-indien-mars-23.png
fichier bien trop gros, réduis le (passe en .webp par ex)
max 100ko

2023-04-20 14:11 UTC, sblondeau commented on src/Controller/ActualityController.php
> +}
tout ça ne fait pas parti de ton US !
toi tu dois juste afficher les actualité coté visiteur, pas gérer le CRUD coté admin
Le crud se fera dans un fichier AdminActualityController dans 4 autres User Stories. 
Enlève tout ce code pour le moment

2023-04-20 14:11 UTC, sblondeau commented on src/Model/ActualityManager.php
> +}
idem pas dans cette US

2023-04-26 12:35 UTC, sblondeau submitted a review, later dismissed

2023-04-26 14:43 UTC, bugBuster42 submitted a review, later dismissed

2023-04-26 16:32 UTC, JorisPineau approved these changes

2023-04-27 15:30 UTC, merged