fixed articles url
WildCodeSchool/202302-orleans-php-project2-ahls pull request #52
Opened 2023-05-09 09:04 UTC by ElBarto444

2023-05-09 09:05 UTC, bugBuster42 submitted a review, later dismissed

2023-05-09 12:35 UTC, sblondeau commented on src/View/Home/index.html.twig
> +						<a href={{ article.url }}>
manque les doubles quotes !

2023-05-09 14:14 UTC, bugBuster42 submitted a review, later dismissed

2023-05-10 08:17 UTC, sblondeau approved these changes

2023-05-10 08:18 UTC, sblondeau requested changes

2023-05-10 08:18 UTC, sblondeau commented on src/View/Home/index.html.twig
> +						<a href="{{ article.url }}">
c'est un lien externe, ajouter une attribut target="_blank" pour que ça ouvre la page dans un nouvel onglet

2023-05-10 08:49 UTC, jaalazard approved these changes

2023-05-10 09:20 UTC, JorisPineau approved these changes

2023-05-10 09:34 UTC, sblondeau approved these changes

2023-05-10 09:34 UTC, merged