S01 u17 partenaires
WildCodeSchool/202302-orleans-php-project2-ahls pull request #6
Opened 2023-04-20 13:39 UTC by jaalazard

2023-04-20 13:41 UTC, bugBuster42 approved these changes

2023-04-20 13:41 UTC, ElBarto444 submitted a review, later dismissed
ok.

2023-04-21 08:28 UTC, sblondeau requested changes
- tu m'as fais tout un CRUD, en plus de ta US qui était juste l'affichage coté visiteur.  donc 4 US en trop ! Je ne veux que le code qui touche à ton US (donc affichage coté site visiteur)
- les images vont être uploadées à terme car admnistrable, donc se trouveront dans public/uploads non versionné. Retire les images pour le moment et utilise plutot une image basique placeholder (que tu affiche si pas d'image), ou tu stylise le "alt" si pas d'image...

2023-04-21 08:28 UTC, sblondeau commented on src/routes.php
> +    // '' => ['HomeController', 'index',],
code commenté à retirer

2023-04-21 09:07 UTC, closed without merging